name: Deploy to Prod server
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      deployment_env: ${{ steps.step2.outputs.DEPLOYMENT_ENV }}
      mode: ${{ steps.step2.outputs.MODE }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect deployment url
        id: step2
        uses: ./.github/actions/detect-deploy-environment
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.deployment_env}}
          OUTPUT2: ${{needs.job1.outputs.mode}}
        run: |
          echo "Deployment ENV detected: $OUTPUT1"
          echo "Mode detected: $OUTPUT2"
